#!/usr/bin/env python
import sys
import global_vars #Global variables in a module
import cmd_line #Command line parsing
import postscript
import geometry
import matrix
import xpm

def main():
	#Parse commandline into globals
	cmd_line.parse(sys.argv)
	
	#Parse ps file into geometric objects
	geometric_objects = postscript.get_geometric_objects(global_vars.ps_file)
	
	#Do transforms
	geometric_objects = geometry.transform_objects(geometric_objects, global_vars.scale, global_vars.rotation_cc, global_vars.trans_x, global_vars.trans_y)
	
	#Clip geometric objects to window
	geometric_objects = geometry.clip_geometric_objects_to_window(geometric_objects, global_vars.lower_bound_x, global_vars.lower_bound_y, global_vars.upper_bound_x, global_vars.upper_bound_y)
	
	#Convert geometric objects into list of points
	points = geometry.geometric_objects_to_points(geometric_objects)
	
	#Convert points to pixel map using view window
	pixel_map = geometry.points_to_pixel_map(points, global_vars.lower_bound_x, global_vars.lower_bound_y, global_vars.upper_bound_x, global_vars.upper_bound_y)
	
	#Write out xpm file
	xpm.do_xpm_write(pixel_map)
	

#Script starts here, call main
main()

#\rm tmp.xpm; ./CG_hw2 -f hw1.ps -a 25 -b 50 -c 399 -d 399 -r 30 -m 100 -n 100 -s 0.5 > tmp.xpm && display tmp.xpm
#\rm tmp.xpm; ./CG_hw2 -f hw2_a.ps -s 1.5 > tmp.xpm && display tmp.xpm
#\rm tmp.xpm; ./CG_hw2 -f hw2_a.ps -m -250 -n -200 > tmp.xpm && display tmp.xpm
#\rm tmp.xpm; ./CG_hw2 -f hw2_b.ps -a 170 -b 100 -c 270 -d 400 > tmp.xpm && display tmp.xpm
#\rm tmp.xpm; ./CG_hw2 -f hw2_b.ps -s 2 > tmp.xpm && display tmp.xpm
#\rm tmp.xpm; ./CG_hw2 -f hw2_c.ps -a 200 -b 100 -c 375 -d 400 > tmp.xpm && display tmp.xpm
#\rm tmp.xpm; ./CG_hw2 -f hw2_c.ps -a 275 -b 100 -c 550 -d 502 > tmp.xpm && display tmp.xpm
